---
sudo: false
language: ruby
rvm:
  - jruby-9.0.5.0
jdk:
  - openjdk7
before_install:
  - gem update --system
  - gem --version
install:
  - cd $TRAVIS_BUILD_DIR/src/logsearch-config
  - gem install rake
  - bin/install-dependencies
script:
  - bin/test
notifications:
  email: false
