---
platform: linux

image: docker:///canopycip/cip-cf-ci

inputs:
- name: logsearch-for-cloudfoundry
- name: logsearch-for-cloudfoundry-version

run:
  path: logsearch-for-cloudfoundry/ci/tasks/build-release.sh

