---
applications:
- name: <%= p('push-kibana.kibana_app_name')%>
  memory: 256M
  instances: 2
  buildpack: nodejs_buildpack
  command: CONFIG_PATH=$HOME/kibana.yml exec node $HOME/bin/kibana.js --port $PORT
  env:
    NODE_ENV: production
    KIBANA_OAUTH2_CLIENT_ID: <%= p('push-kibana.kibana_oauth2_client_id')%>
    KIBANA_OAUTH2_CLIENT_SECRET: "<%= p('push-kibana.kibana_oauth2_client_secret')%>"