---
applications:
- name: <%= p('push-kibana.app_name')%>
  memory: <%= p('push-kibana.app_memory')%>
  instances: <%= p('push-kibana.app_instances')%>
  domain: <%= p('cloudfoundry.system_domain')%>
  buildpack: nodejs_buildpack
  command: $HOME/bin/kibana --port $PORT 
  env:
    NODE_ENV: production
    KIBANA_OAUTH2_CLIENT_ID: "<%= p('push-kibana.oauth2_client_id')%>"
    KIBANA_OAUTH2_CLIENT_SECRET: "<%= p('push-kibana.oauth2_client_secret')%>"
    CF_API_URI: "https://api.<%= p('cloudfoundry.system_domain')%>" 
    SKIP_SSL_VALIDATION: <%= p('cloudfoundry.skip_ssl_validation')%> 
