---
applications:
- name: <%= p('push-kibana.app_name')%>
  memory: <%= p('push-kibana.app_memory')%>
  instances: <%= p('push-kibana.app_instances')%>
  no-hostname: <%= p('push-kibana.app_no_hostname')%>
  domain: <%= p('cloudfoundry.apps_domain')%>
  buildpack: binary_buildpack
  command: bash -c "\$HOME/bin/kibana --port \$PORT & pid=\$!; while true; do [ \$(ps uh \$pid | awk '{print \$6}') -gt 300000 ] && { echo memory limit reached, recycling instance; exit 1; }; sleep 1; done"
  timeout: 180
  env:
    NODE_ENV: production
    KIBANA_OAUTH2_CLIENT_ID: "<%= p('push-kibana.oauth2_client_id')%>"
    KIBANA_OAUTH2_CLIENT_SECRET: "<%= p('push-kibana.oauth2_client_secret')%>"
    CF_API_URI: "https://api.<%= p('cloudfoundry.system_domain')%>"
    CF_SYSTEM_ORG: "<%= p('cloudfoundry.system_org')%>"
    SKIP_SSL_VALIDATION: <%= p('cloudfoundry.skip_ssl_validation')%>
    REDIS_HOST: <%= p('redis.host')%>
